---
language: node_js
node_js:
  - 12
sudo: false
cache:
  npm: true
  directories:
    - node_modules
services:
  - xvfb
before_install:
  - cd front
before_script:
  - npm install
after_success: npm run test
