---
language: node_js
node_js:
- 8
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
after_success: npm run test
