// flow-typed signature: e0159660cecbd50d98f58d0d797fb10f
// flow-typed version: <<STUB>>/@types/axios_v^0.14.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/axios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/axios' {
  declare module.exports: any;
}
