// flow-typed signature: 2897e9d8f70c688cf8ff0b569b3431fd
// flow-typed version: <<STUB>>/@types/body-parser_v^1.17.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/body-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/body-parser' {
  declare module.exports: any;
}
