// flow-typed signature: 286339b1a2df31ed55472431d2499d45
// flow-typed version: <<STUB>>/@types/classnames_v^2.2.6/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/classnames'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/classnames' {
  declare module.exports: any;
}
