// flow-typed signature: 1bff62e2162bb8ca1f0677bf68ae362f
// flow-typed version: <<STUB>>/@types/compression_v^0.0.36/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/compression'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/compression' {
  declare module.exports: any;
}
