// flow-typed signature: e5f85cd10d3b6726134b9b54550d0472
// flow-typed version: <<STUB>>/@types/enzyme_v^3.1.13/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/enzyme' {
  declare module.exports: any;
}
