// flow-typed signature: e7249c4203dbb0adf6529df2230e9099
// flow-typed version: <<STUB>>/@types/express-rate-limit_v^2.9.3/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/express-rate-limit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/express-rate-limit' {
  declare module.exports: any;
}
