// flow-typed signature: f94d8fc15ad87a762d8d9500c00f5b50
// flow-typed version: <<STUB>>/@types/express_v^4.16.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/express' {
  declare module.exports: any;
}
