// flow-typed signature: bc9ce4aaef9e29c793b49b2af87aa7da
// flow-typed version: <<STUB>>/@types/fetch-mock_v^6.0.3/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/fetch-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/fetch-mock' {
  declare module.exports: any;
}
