// flow-typed signature: 19aec8ee29133785e2a5c36adbcc43bd
// flow-typed version: <<STUB>>/@types/jest_v^23.3.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
