// flow-typed signature: 2d974f0cf1e4b286e19b6494ba4ba451
// flow-typed version: <<STUB>>/@types/jwt-decode_v^2.2.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jwt-decode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jwt-decode' {
  declare module.exports: any;
}
