// flow-typed signature: bbf8040e37364e92e09121d7b573dc8e
// flow-typed version: <<STUB>>/@types/react-motion_v^0.0.26/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-motion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-motion' {
  declare module.exports: any;
}
