// flow-typed signature: af406182fe2bfdb45fd3dd2c0d83842d
// flow-typed version: <<STUB>>/@types/react-router_v^4.0.30/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-router' {
  declare module.exports: any;
}
