// flow-typed signature: 9a62f272c07409963455204eb446472d
// flow-typed version: <<STUB>>/@types/redux-persist_v^4.3.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/redux-persist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/redux-persist' {
  declare module.exports: any;
}
