// flow-typed signature: 05a039caf3d59844dc6ee58c16eb366b
// flow-typed version: <<STUB>>/@types/redux-logger_v^3.0.6/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/redux-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/redux-logger' {
  declare module.exports: any;
}
