// flow-typed signature: 8826d62e708776c60b5e42ecd8947013
// flow-typed version: <<STUB>>/@types/redux-mock-store_v^1.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/redux-mock-store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/redux-mock-store' {
  declare module.exports: any;
}
