// flow-typed signature: 62028e448de84254d6a7cb471a70fc36
// flow-typed version: <<STUB>>/@types/rename_v^1.0.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/rename'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/rename' {
  declare module.exports: any;
}
