// flow-typed signature: 7c16e4689a386ffe9d2b8db4a2c2c94c
// flow-typed version: <<STUB>>/@types/rimraf_v^2.0.2/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/rimraf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/rimraf' {
  declare module.exports: any;
}
