// flow-typed signature: f512ace07a06ac1f16b6ea68145155ab
// flow-typed version: <<STUB>>/@types/styled-components_v^4.1.18/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/styled-components' {
  declare module.exports: any;
}
