// flow-typed signature: 1bbbffe9ea74f9dfd2ad237326179cab
// flow-typed version: <<STUB>>/@types/webpack_v^4.4.9/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/webpack' {
  declare module.exports: any;
}
