// flow-typed signature: 7f96df93d8a4bb6b6b7bc348e3668d6a
// flow-typed version: <<STUB>>/font-awesome_v^4.7.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'font-awesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'font-awesome' {
  declare module.exports: any;
}
