// flow-typed signature: 10751cc9e520f00e5f8904b43d52bce3
// flow-typed version: <<STUB>>/modernizr_v^3.6.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'modernizr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'modernizr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'modernizr/feature-detects/a/download' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/ambientlight' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/applicationcache' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/audio' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/audio/autoplay' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/audio/loop' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/audio/preload' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/audio/webaudio' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/battery' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/battery/lowbattery' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/blob' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/canvas' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/canvas/blending' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/canvas/todataurl' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/canvas/winding' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/canvastext' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/contenteditable' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/contextmenu' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/cookies' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/cors' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/crypto' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/crypto/getrandomvalues' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/all' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/animations' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/appearance' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/backdropfilter' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/backgroundblendmode' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/backgroundcliptext' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/backgroundposition-shorthand' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/backgroundposition-xy' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/backgroundrepeat' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/backgroundsize' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/backgroundsizecover' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/borderimage' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/borderradius' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/boxdecorationbreak' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/boxshadow' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/boxsizing' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/calc' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/checked' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/chunit' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/columns' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/cssgrid' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/cubicbezierrange' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/customproperties' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/displayrunin' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/displaytable' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/ellipsis' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/escape' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/exunit' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/filters' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/flexbox' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/flexboxlegacy' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/flexboxtweener' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/flexwrap' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/focuswithin' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/fontdisplay' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/fontface' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/generatedcontent' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/gradients' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/hairline' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/hsla' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/hyphens' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/invalid' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/lastchild' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/mask' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/mediaqueries' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/multiplebgs' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/nthchild' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/objectfit' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/opacity' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/overflow-scrolling' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/pointerevents' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/positionsticky' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/pseudoanimations' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/pseudotransitions' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/reflections' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/regions' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/remunit' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/resize' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/rgba' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/scrollbars' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/scrollsnappoints' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/shapes' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/siblinggeneral' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/subpixelfont' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/supports' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/target' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/textalignlast' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/textdecoration' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/textshadow' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/transforms' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/transforms3d' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/transformslevel2' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/transformstylepreserve3d' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/transitions' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/userselect' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/valid' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/variablefonts' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/vhunit' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/vmaxunit' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/vminunit' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/vwunit' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/will-change' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/css/wrapflow' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/custom-elements' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/custom-protocol-handler' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/customevent' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/dart' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/dataview-api' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/dom/classlist' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/dom/createElement-attrs' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/dom/dataset' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/dom/documentfragment' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/dom/hidden' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/dom/intersection-observer' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/dom/microdata' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/dom/mutationObserver' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/dom/passiveeventlisteners' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/elem/bdi' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/elem/datalist' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/elem/details' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/elem/output' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/elem/picture' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/elem/progress-meter' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/elem/ruby' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/elem/template' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/elem/time' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/elem/track' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/elem/unknown' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/emoji' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es5/array' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es5/date' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es5/function' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es5/object' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es5/specification' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es5/strictmode' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es5/string' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es5/syntax' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es5/undefined' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es6/array' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es6/arrow' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es6/collections' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es6/contains' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es6/generators' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es6/math' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es6/number' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es6/object' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es6/promises' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/es6/string' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/event/deviceorientation-motion' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/event/oninput' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/eventlistener' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/exif-orientation' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/file/api' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/file/filesystem' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/flash' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/forcetouch' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/forms/capture' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/forms/fileinput' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/forms/fileinputdirectory' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/forms/formattribute' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/forms/inputnumber-l10n' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/forms/placeholder' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/forms/requestautocomplete' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/forms/validation' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/fullscreen-api' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/gamepad' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/geolocation' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/hashchange' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/hiddenscroll' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/history' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/htmlimports' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/ie8compat' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/iframe/sandbox' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/iframe/seamless' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/iframe/srcdoc' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/img/apng' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/img/crossorigin' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/img/jpeg2000' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/img/jpegxr' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/img/sizes' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/img/srcset' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/img/webp-alpha' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/img/webp-animation' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/img/webp-lossless' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/img/webp' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/indexeddb' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/indexeddbblob' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/input' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/input/formaction' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/input/formenctype' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/input/formmethod' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/input/formnovalidate' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/input/formtarget' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/inputsearchevent' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/inputtypes' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/intl' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/json' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/ligatures' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/lists-reversed' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/mathml' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/media-source-extension-api' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/mediaquery/hovermq' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/mediaquery/pointermq' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/messagechannel' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/network/beacon' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/network/connection-effectivetype' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/network/connection' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/network/eventsource' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/network/fetch' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/network/xhr-responsetype-arraybuffer' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/network/xhr-responsetype-blob' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/network/xhr-responsetype-document' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/network/xhr-responsetype-json' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/network/xhr-responsetype-text' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/network/xhr-responsetype' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/network/xhr2' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/notification' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/pagevisibility-api' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/performance' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/pointerevents' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/pointerlock-api' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/postmessage' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/proximity' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/queryselector' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/quota-management-api' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/requestanimationframe' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/script/async' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/script/defer' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/serviceworker' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/speech/speech-recognition' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/speech/speech-synthesis' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/storage/localstorage' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/storage/sessionstorage' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/storage/websqldatabase' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/style/scoped' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/svg' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/svg/asimg' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/svg/clippaths' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/svg/filters' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/svg/foreignobject' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/svg/inline' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/svg/smil' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/templatestrings' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/textarea/maxlength' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/touchevents' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/typed-arrays' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/unicode-range' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/unicode' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/url/bloburls' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/url/data-uri' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/url/parser' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/url/urlsearchparams' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/userdata' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/vibration' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/video' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/video/autoplay' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/video/crossorigin' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/video/loop' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/video/preload' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/vml' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/web-intents' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/webanimations' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/webauthn/publickeycredential' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/webgl' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/webgl/extensions' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/webrtc/datachannel' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/webrtc/getusermedia' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/webrtc/peerconnection' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/websockets' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/websockets/binary' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/window/atob-btoa' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/window/framed' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/window/matchmedia' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/workers/blobworkers' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/workers/dataworkers' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/workers/sharedworkers' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/workers/transferables' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/workers/webworkers' {
  declare module.exports: any;
}

declare module 'modernizr/feature-detects/xdomainrequest' {
  declare module.exports: any;
}

declare module 'modernizr/lib/build-query' {
  declare module.exports: any;
}

declare module 'modernizr/lib/build' {
  declare module.exports: any;
}

declare module 'modernizr/lib/cli' {
  declare module.exports: any;
}

declare module 'modernizr/lib/generate-banner' {
  declare module.exports: any;
}

declare module 'modernizr/lib/generate-license' {
  declare module.exports: any;
}

declare module 'modernizr/lib/metadata' {
  declare module.exports: any;
}

declare module 'modernizr/lib/options' {
  declare module.exports: any;
}

declare module 'modernizr/src/addTest' {
  declare module.exports: any;
}

declare module 'modernizr/src/atRule' {
  declare module.exports: any;
}

declare module 'modernizr/src/classes' {
  declare module.exports: any;
}

declare module 'modernizr/src/computedStyle' {
  declare module.exports: any;
}

declare module 'modernizr/src/contains' {
  declare module.exports: any;
}

declare module 'modernizr/src/createElement' {
  declare module.exports: any;
}

declare module 'modernizr/src/cssomPrefixes' {
  declare module.exports: any;
}

declare module 'modernizr/src/cssToDOM' {
  declare module.exports: any;
}

declare module 'modernizr/src/docElement' {
  declare module.exports: any;
}

declare module 'modernizr/src/domPrefixes' {
  declare module.exports: any;
}

declare module 'modernizr/src/domToCSS' {
  declare module.exports: any;
}

declare module 'modernizr/src/fnBind' {
  declare module.exports: any;
}

declare module 'modernizr/src/generate' {
  declare module.exports: any;
}

declare module 'modernizr/src/getBody' {
  declare module.exports: any;
}

declare module 'modernizr/src/hasEvent' {
  declare module.exports: any;
}

declare module 'modernizr/src/hasOwnProp' {
  declare module.exports: any;
}

declare module 'modernizr/src/html5printshiv' {
  declare module.exports: any;
}

declare module 'modernizr/src/html5shiv' {
  declare module.exports: any;
}

declare module 'modernizr/src/injectElementWithStyles' {
  declare module.exports: any;
}

declare module 'modernizr/src/inputElem' {
  declare module.exports: any;
}

declare module 'modernizr/src/is' {
  declare module.exports: any;
}

declare module 'modernizr/src/isSVG' {
  declare module.exports: any;
}

declare module 'modernizr/src/load' {
  declare module.exports: any;
}

declare module 'modernizr/src/modElem' {
  declare module.exports: any;
}

declare module 'modernizr/src/Modernizr' {
  declare module.exports: any;
}

declare module 'modernizr/src/ModernizrProto' {
  declare module.exports: any;
}

declare module 'modernizr/src/mq' {
  declare module.exports: any;
}

declare module 'modernizr/src/mStyle' {
  declare module.exports: any;
}

declare module 'modernizr/src/nativeTestProps' {
  declare module.exports: any;
}

declare module 'modernizr/src/omPrefixes' {
  declare module.exports: any;
}

declare module 'modernizr/src/prefixed' {
  declare module.exports: any;
}

declare module 'modernizr/src/prefixedCSS' {
  declare module.exports: any;
}

declare module 'modernizr/src/prefixedCSSValue' {
  declare module.exports: any;
}

declare module 'modernizr/src/prefixes' {
  declare module.exports: any;
}

declare module 'modernizr/src/roundedEquals' {
  declare module.exports: any;
}

declare module 'modernizr/src/setClasses' {
  declare module.exports: any;
}

declare module 'modernizr/src/slice' {
  declare module.exports: any;
}

declare module 'modernizr/src/testAllProps' {
  declare module.exports: any;
}

declare module 'modernizr/src/testDOMProps' {
  declare module.exports: any;
}

declare module 'modernizr/src/testProp' {
  declare module.exports: any;
}

declare module 'modernizr/src/testProps' {
  declare module.exports: any;
}

declare module 'modernizr/src/testPropsAll' {
  declare module.exports: any;
}

declare module 'modernizr/src/testRunner' {
  declare module.exports: any;
}

declare module 'modernizr/src/tests' {
  declare module.exports: any;
}

declare module 'modernizr/src/testStyles' {
  declare module.exports: any;
}

declare module 'modernizr/src/testXhrType' {
  declare module.exports: any;
}

declare module 'modernizr/src/toStringFn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'modernizr/feature-detects/a/download.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/a/download'>;
}
declare module 'modernizr/feature-detects/ambientlight.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/ambientlight'>;
}
declare module 'modernizr/feature-detects/applicationcache.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/applicationcache'>;
}
declare module 'modernizr/feature-detects/audio.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/audio'>;
}
declare module 'modernizr/feature-detects/audio/autoplay.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/audio/autoplay'>;
}
declare module 'modernizr/feature-detects/audio/loop.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/audio/loop'>;
}
declare module 'modernizr/feature-detects/audio/preload.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/audio/preload'>;
}
declare module 'modernizr/feature-detects/audio/webaudio.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/audio/webaudio'>;
}
declare module 'modernizr/feature-detects/battery.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/battery'>;
}
declare module 'modernizr/feature-detects/battery/lowbattery.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/battery/lowbattery'>;
}
declare module 'modernizr/feature-detects/blob.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/blob'>;
}
declare module 'modernizr/feature-detects/canvas.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/canvas'>;
}
declare module 'modernizr/feature-detects/canvas/blending.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/canvas/blending'>;
}
declare module 'modernizr/feature-detects/canvas/todataurl.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/canvas/todataurl'>;
}
declare module 'modernizr/feature-detects/canvas/winding.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/canvas/winding'>;
}
declare module 'modernizr/feature-detects/canvastext.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/canvastext'>;
}
declare module 'modernizr/feature-detects/contenteditable.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/contenteditable'>;
}
declare module 'modernizr/feature-detects/contextmenu.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/contextmenu'>;
}
declare module 'modernizr/feature-detects/cookies.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/cookies'>;
}
declare module 'modernizr/feature-detects/cors.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/cors'>;
}
declare module 'modernizr/feature-detects/crypto.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/crypto'>;
}
declare module 'modernizr/feature-detects/crypto/getrandomvalues.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/crypto/getrandomvalues'>;
}
declare module 'modernizr/feature-detects/css/all.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/all'>;
}
declare module 'modernizr/feature-detects/css/animations.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/animations'>;
}
declare module 'modernizr/feature-detects/css/appearance.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/appearance'>;
}
declare module 'modernizr/feature-detects/css/backdropfilter.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/backdropfilter'>;
}
declare module 'modernizr/feature-detects/css/backgroundblendmode.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/backgroundblendmode'>;
}
declare module 'modernizr/feature-detects/css/backgroundcliptext.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/backgroundcliptext'>;
}
declare module 'modernizr/feature-detects/css/backgroundposition-shorthand.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/backgroundposition-shorthand'>;
}
declare module 'modernizr/feature-detects/css/backgroundposition-xy.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/backgroundposition-xy'>;
}
declare module 'modernizr/feature-detects/css/backgroundrepeat.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/backgroundrepeat'>;
}
declare module 'modernizr/feature-detects/css/backgroundsize.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/backgroundsize'>;
}
declare module 'modernizr/feature-detects/css/backgroundsizecover.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/backgroundsizecover'>;
}
declare module 'modernizr/feature-detects/css/borderimage.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/borderimage'>;
}
declare module 'modernizr/feature-detects/css/borderradius.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/borderradius'>;
}
declare module 'modernizr/feature-detects/css/boxdecorationbreak.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/boxdecorationbreak'>;
}
declare module 'modernizr/feature-detects/css/boxshadow.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/boxshadow'>;
}
declare module 'modernizr/feature-detects/css/boxsizing.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/boxsizing'>;
}
declare module 'modernizr/feature-detects/css/calc.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/calc'>;
}
declare module 'modernizr/feature-detects/css/checked.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/checked'>;
}
declare module 'modernizr/feature-detects/css/chunit.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/chunit'>;
}
declare module 'modernizr/feature-detects/css/columns.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/columns'>;
}
declare module 'modernizr/feature-detects/css/cssgrid.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/cssgrid'>;
}
declare module 'modernizr/feature-detects/css/cubicbezierrange.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/cubicbezierrange'>;
}
declare module 'modernizr/feature-detects/css/customproperties.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/customproperties'>;
}
declare module 'modernizr/feature-detects/css/displayrunin.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/displayrunin'>;
}
declare module 'modernizr/feature-detects/css/displaytable.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/displaytable'>;
}
declare module 'modernizr/feature-detects/css/ellipsis.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/ellipsis'>;
}
declare module 'modernizr/feature-detects/css/escape.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/escape'>;
}
declare module 'modernizr/feature-detects/css/exunit.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/exunit'>;
}
declare module 'modernizr/feature-detects/css/filters.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/filters'>;
}
declare module 'modernizr/feature-detects/css/flexbox.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/flexbox'>;
}
declare module 'modernizr/feature-detects/css/flexboxlegacy.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/flexboxlegacy'>;
}
declare module 'modernizr/feature-detects/css/flexboxtweener.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/flexboxtweener'>;
}
declare module 'modernizr/feature-detects/css/flexwrap.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/flexwrap'>;
}
declare module 'modernizr/feature-detects/css/focuswithin.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/focuswithin'>;
}
declare module 'modernizr/feature-detects/css/fontdisplay.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/fontdisplay'>;
}
declare module 'modernizr/feature-detects/css/fontface.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/fontface'>;
}
declare module 'modernizr/feature-detects/css/generatedcontent.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/generatedcontent'>;
}
declare module 'modernizr/feature-detects/css/gradients.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/gradients'>;
}
declare module 'modernizr/feature-detects/css/hairline.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/hairline'>;
}
declare module 'modernizr/feature-detects/css/hsla.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/hsla'>;
}
declare module 'modernizr/feature-detects/css/hyphens.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/hyphens'>;
}
declare module 'modernizr/feature-detects/css/invalid.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/invalid'>;
}
declare module 'modernizr/feature-detects/css/lastchild.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/lastchild'>;
}
declare module 'modernizr/feature-detects/css/mask.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/mask'>;
}
declare module 'modernizr/feature-detects/css/mediaqueries.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/mediaqueries'>;
}
declare module 'modernizr/feature-detects/css/multiplebgs.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/multiplebgs'>;
}
declare module 'modernizr/feature-detects/css/nthchild.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/nthchild'>;
}
declare module 'modernizr/feature-detects/css/objectfit.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/objectfit'>;
}
declare module 'modernizr/feature-detects/css/opacity.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/opacity'>;
}
declare module 'modernizr/feature-detects/css/overflow-scrolling.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/overflow-scrolling'>;
}
declare module 'modernizr/feature-detects/css/pointerevents.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/pointerevents'>;
}
declare module 'modernizr/feature-detects/css/positionsticky.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/positionsticky'>;
}
declare module 'modernizr/feature-detects/css/pseudoanimations.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/pseudoanimations'>;
}
declare module 'modernizr/feature-detects/css/pseudotransitions.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/pseudotransitions'>;
}
declare module 'modernizr/feature-detects/css/reflections.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/reflections'>;
}
declare module 'modernizr/feature-detects/css/regions.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/regions'>;
}
declare module 'modernizr/feature-detects/css/remunit.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/remunit'>;
}
declare module 'modernizr/feature-detects/css/resize.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/resize'>;
}
declare module 'modernizr/feature-detects/css/rgba.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/rgba'>;
}
declare module 'modernizr/feature-detects/css/scrollbars.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/scrollbars'>;
}
declare module 'modernizr/feature-detects/css/scrollsnappoints.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/scrollsnappoints'>;
}
declare module 'modernizr/feature-detects/css/shapes.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/shapes'>;
}
declare module 'modernizr/feature-detects/css/siblinggeneral.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/siblinggeneral'>;
}
declare module 'modernizr/feature-detects/css/subpixelfont.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/subpixelfont'>;
}
declare module 'modernizr/feature-detects/css/supports.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/supports'>;
}
declare module 'modernizr/feature-detects/css/target.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/target'>;
}
declare module 'modernizr/feature-detects/css/textalignlast.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/textalignlast'>;
}
declare module 'modernizr/feature-detects/css/textdecoration.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/textdecoration'>;
}
declare module 'modernizr/feature-detects/css/textshadow.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/textshadow'>;
}
declare module 'modernizr/feature-detects/css/transforms.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/transforms'>;
}
declare module 'modernizr/feature-detects/css/transforms3d.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/transforms3d'>;
}
declare module 'modernizr/feature-detects/css/transformslevel2.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/transformslevel2'>;
}
declare module 'modernizr/feature-detects/css/transformstylepreserve3d.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/transformstylepreserve3d'>;
}
declare module 'modernizr/feature-detects/css/transitions.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/transitions'>;
}
declare module 'modernizr/feature-detects/css/userselect.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/userselect'>;
}
declare module 'modernizr/feature-detects/css/valid.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/valid'>;
}
declare module 'modernizr/feature-detects/css/variablefonts.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/variablefonts'>;
}
declare module 'modernizr/feature-detects/css/vhunit.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/vhunit'>;
}
declare module 'modernizr/feature-detects/css/vmaxunit.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/vmaxunit'>;
}
declare module 'modernizr/feature-detects/css/vminunit.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/vminunit'>;
}
declare module 'modernizr/feature-detects/css/vwunit.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/vwunit'>;
}
declare module 'modernizr/feature-detects/css/will-change.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/will-change'>;
}
declare module 'modernizr/feature-detects/css/wrapflow.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/css/wrapflow'>;
}
declare module 'modernizr/feature-detects/custom-elements.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/custom-elements'>;
}
declare module 'modernizr/feature-detects/custom-protocol-handler.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/custom-protocol-handler'>;
}
declare module 'modernizr/feature-detects/customevent.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/customevent'>;
}
declare module 'modernizr/feature-detects/dart.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/dart'>;
}
declare module 'modernizr/feature-detects/dataview-api.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/dataview-api'>;
}
declare module 'modernizr/feature-detects/dom/classlist.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/dom/classlist'>;
}
declare module 'modernizr/feature-detects/dom/createElement-attrs.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/dom/createElement-attrs'>;
}
declare module 'modernizr/feature-detects/dom/dataset.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/dom/dataset'>;
}
declare module 'modernizr/feature-detects/dom/documentfragment.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/dom/documentfragment'>;
}
declare module 'modernizr/feature-detects/dom/hidden.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/dom/hidden'>;
}
declare module 'modernizr/feature-detects/dom/intersection-observer.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/dom/intersection-observer'>;
}
declare module 'modernizr/feature-detects/dom/microdata.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/dom/microdata'>;
}
declare module 'modernizr/feature-detects/dom/mutationObserver.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/dom/mutationObserver'>;
}
declare module 'modernizr/feature-detects/dom/passiveeventlisteners.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/dom/passiveeventlisteners'>;
}
declare module 'modernizr/feature-detects/elem/bdi.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/elem/bdi'>;
}
declare module 'modernizr/feature-detects/elem/datalist.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/elem/datalist'>;
}
declare module 'modernizr/feature-detects/elem/details.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/elem/details'>;
}
declare module 'modernizr/feature-detects/elem/output.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/elem/output'>;
}
declare module 'modernizr/feature-detects/elem/picture.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/elem/picture'>;
}
declare module 'modernizr/feature-detects/elem/progress-meter.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/elem/progress-meter'>;
}
declare module 'modernizr/feature-detects/elem/ruby.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/elem/ruby'>;
}
declare module 'modernizr/feature-detects/elem/template.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/elem/template'>;
}
declare module 'modernizr/feature-detects/elem/time.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/elem/time'>;
}
declare module 'modernizr/feature-detects/elem/track.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/elem/track'>;
}
declare module 'modernizr/feature-detects/elem/unknown.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/elem/unknown'>;
}
declare module 'modernizr/feature-detects/emoji.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/emoji'>;
}
declare module 'modernizr/feature-detects/es5/array.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es5/array'>;
}
declare module 'modernizr/feature-detects/es5/date.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es5/date'>;
}
declare module 'modernizr/feature-detects/es5/function.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es5/function'>;
}
declare module 'modernizr/feature-detects/es5/object.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es5/object'>;
}
declare module 'modernizr/feature-detects/es5/specification.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es5/specification'>;
}
declare module 'modernizr/feature-detects/es5/strictmode.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es5/strictmode'>;
}
declare module 'modernizr/feature-detects/es5/string.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es5/string'>;
}
declare module 'modernizr/feature-detects/es5/syntax.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es5/syntax'>;
}
declare module 'modernizr/feature-detects/es5/undefined.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es5/undefined'>;
}
declare module 'modernizr/feature-detects/es6/array.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es6/array'>;
}
declare module 'modernizr/feature-detects/es6/arrow.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es6/arrow'>;
}
declare module 'modernizr/feature-detects/es6/collections.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es6/collections'>;
}
declare module 'modernizr/feature-detects/es6/contains.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es6/contains'>;
}
declare module 'modernizr/feature-detects/es6/generators.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es6/generators'>;
}
declare module 'modernizr/feature-detects/es6/math.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es6/math'>;
}
declare module 'modernizr/feature-detects/es6/number.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es6/number'>;
}
declare module 'modernizr/feature-detects/es6/object.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es6/object'>;
}
declare module 'modernizr/feature-detects/es6/promises.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es6/promises'>;
}
declare module 'modernizr/feature-detects/es6/string.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/es6/string'>;
}
declare module 'modernizr/feature-detects/event/deviceorientation-motion.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/event/deviceorientation-motion'>;
}
declare module 'modernizr/feature-detects/event/oninput.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/event/oninput'>;
}
declare module 'modernizr/feature-detects/eventlistener.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/eventlistener'>;
}
declare module 'modernizr/feature-detects/exif-orientation.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/exif-orientation'>;
}
declare module 'modernizr/feature-detects/file/api.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/file/api'>;
}
declare module 'modernizr/feature-detects/file/filesystem.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/file/filesystem'>;
}
declare module 'modernizr/feature-detects/flash.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/flash'>;
}
declare module 'modernizr/feature-detects/forcetouch.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/forcetouch'>;
}
declare module 'modernizr/feature-detects/forms/capture.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/forms/capture'>;
}
declare module 'modernizr/feature-detects/forms/fileinput.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/forms/fileinput'>;
}
declare module 'modernizr/feature-detects/forms/fileinputdirectory.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/forms/fileinputdirectory'>;
}
declare module 'modernizr/feature-detects/forms/formattribute.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/forms/formattribute'>;
}
declare module 'modernizr/feature-detects/forms/inputnumber-l10n.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/forms/inputnumber-l10n'>;
}
declare module 'modernizr/feature-detects/forms/placeholder.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/forms/placeholder'>;
}
declare module 'modernizr/feature-detects/forms/requestautocomplete.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/forms/requestautocomplete'>;
}
declare module 'modernizr/feature-detects/forms/validation.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/forms/validation'>;
}
declare module 'modernizr/feature-detects/fullscreen-api.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/fullscreen-api'>;
}
declare module 'modernizr/feature-detects/gamepad.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/gamepad'>;
}
declare module 'modernizr/feature-detects/geolocation.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/geolocation'>;
}
declare module 'modernizr/feature-detects/hashchange.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/hashchange'>;
}
declare module 'modernizr/feature-detects/hiddenscroll.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/hiddenscroll'>;
}
declare module 'modernizr/feature-detects/history.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/history'>;
}
declare module 'modernizr/feature-detects/htmlimports.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/htmlimports'>;
}
declare module 'modernizr/feature-detects/ie8compat.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/ie8compat'>;
}
declare module 'modernizr/feature-detects/iframe/sandbox.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/iframe/sandbox'>;
}
declare module 'modernizr/feature-detects/iframe/seamless.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/iframe/seamless'>;
}
declare module 'modernizr/feature-detects/iframe/srcdoc.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/iframe/srcdoc'>;
}
declare module 'modernizr/feature-detects/img/apng.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/img/apng'>;
}
declare module 'modernizr/feature-detects/img/crossorigin.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/img/crossorigin'>;
}
declare module 'modernizr/feature-detects/img/jpeg2000.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/img/jpeg2000'>;
}
declare module 'modernizr/feature-detects/img/jpegxr.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/img/jpegxr'>;
}
declare module 'modernizr/feature-detects/img/sizes.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/img/sizes'>;
}
declare module 'modernizr/feature-detects/img/srcset.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/img/srcset'>;
}
declare module 'modernizr/feature-detects/img/webp-alpha.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/img/webp-alpha'>;
}
declare module 'modernizr/feature-detects/img/webp-animation.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/img/webp-animation'>;
}
declare module 'modernizr/feature-detects/img/webp-lossless.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/img/webp-lossless'>;
}
declare module 'modernizr/feature-detects/img/webp.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/img/webp'>;
}
declare module 'modernizr/feature-detects/indexeddb.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/indexeddb'>;
}
declare module 'modernizr/feature-detects/indexeddbblob.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/indexeddbblob'>;
}
declare module 'modernizr/feature-detects/input.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/input'>;
}
declare module 'modernizr/feature-detects/input/formaction.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/input/formaction'>;
}
declare module 'modernizr/feature-detects/input/formenctype.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/input/formenctype'>;
}
declare module 'modernizr/feature-detects/input/formmethod.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/input/formmethod'>;
}
declare module 'modernizr/feature-detects/input/formnovalidate.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/input/formnovalidate'>;
}
declare module 'modernizr/feature-detects/input/formtarget.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/input/formtarget'>;
}
declare module 'modernizr/feature-detects/inputsearchevent.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/inputsearchevent'>;
}
declare module 'modernizr/feature-detects/inputtypes.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/inputtypes'>;
}
declare module 'modernizr/feature-detects/intl.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/intl'>;
}
declare module 'modernizr/feature-detects/json.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/json'>;
}
declare module 'modernizr/feature-detects/ligatures.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/ligatures'>;
}
declare module 'modernizr/feature-detects/lists-reversed.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/lists-reversed'>;
}
declare module 'modernizr/feature-detects/mathml.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/mathml'>;
}
declare module 'modernizr/feature-detects/media-source-extension-api.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/media-source-extension-api'>;
}
declare module 'modernizr/feature-detects/mediaquery/hovermq.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/mediaquery/hovermq'>;
}
declare module 'modernizr/feature-detects/mediaquery/pointermq.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/mediaquery/pointermq'>;
}
declare module 'modernizr/feature-detects/messagechannel.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/messagechannel'>;
}
declare module 'modernizr/feature-detects/network/beacon.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/network/beacon'>;
}
declare module 'modernizr/feature-detects/network/connection-effectivetype.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/network/connection-effectivetype'>;
}
declare module 'modernizr/feature-detects/network/connection.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/network/connection'>;
}
declare module 'modernizr/feature-detects/network/eventsource.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/network/eventsource'>;
}
declare module 'modernizr/feature-detects/network/fetch.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/network/fetch'>;
}
declare module 'modernizr/feature-detects/network/xhr-responsetype-arraybuffer.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/network/xhr-responsetype-arraybuffer'>;
}
declare module 'modernizr/feature-detects/network/xhr-responsetype-blob.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/network/xhr-responsetype-blob'>;
}
declare module 'modernizr/feature-detects/network/xhr-responsetype-document.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/network/xhr-responsetype-document'>;
}
declare module 'modernizr/feature-detects/network/xhr-responsetype-json.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/network/xhr-responsetype-json'>;
}
declare module 'modernizr/feature-detects/network/xhr-responsetype-text.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/network/xhr-responsetype-text'>;
}
declare module 'modernizr/feature-detects/network/xhr-responsetype.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/network/xhr-responsetype'>;
}
declare module 'modernizr/feature-detects/network/xhr2.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/network/xhr2'>;
}
declare module 'modernizr/feature-detects/notification.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/notification'>;
}
declare module 'modernizr/feature-detects/pagevisibility-api.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/pagevisibility-api'>;
}
declare module 'modernizr/feature-detects/performance.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/performance'>;
}
declare module 'modernizr/feature-detects/pointerevents.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/pointerevents'>;
}
declare module 'modernizr/feature-detects/pointerlock-api.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/pointerlock-api'>;
}
declare module 'modernizr/feature-detects/postmessage.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/postmessage'>;
}
declare module 'modernizr/feature-detects/proximity.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/proximity'>;
}
declare module 'modernizr/feature-detects/queryselector.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/queryselector'>;
}
declare module 'modernizr/feature-detects/quota-management-api.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/quota-management-api'>;
}
declare module 'modernizr/feature-detects/requestanimationframe.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/requestanimationframe'>;
}
declare module 'modernizr/feature-detects/script/async.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/script/async'>;
}
declare module 'modernizr/feature-detects/script/defer.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/script/defer'>;
}
declare module 'modernizr/feature-detects/serviceworker.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/serviceworker'>;
}
declare module 'modernizr/feature-detects/speech/speech-recognition.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/speech/speech-recognition'>;
}
declare module 'modernizr/feature-detects/speech/speech-synthesis.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/speech/speech-synthesis'>;
}
declare module 'modernizr/feature-detects/storage/localstorage.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/storage/localstorage'>;
}
declare module 'modernizr/feature-detects/storage/sessionstorage.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/storage/sessionstorage'>;
}
declare module 'modernizr/feature-detects/storage/websqldatabase.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/storage/websqldatabase'>;
}
declare module 'modernizr/feature-detects/style/scoped.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/style/scoped'>;
}
declare module 'modernizr/feature-detects/svg.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/svg'>;
}
declare module 'modernizr/feature-detects/svg/asimg.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/svg/asimg'>;
}
declare module 'modernizr/feature-detects/svg/clippaths.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/svg/clippaths'>;
}
declare module 'modernizr/feature-detects/svg/filters.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/svg/filters'>;
}
declare module 'modernizr/feature-detects/svg/foreignobject.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/svg/foreignobject'>;
}
declare module 'modernizr/feature-detects/svg/inline.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/svg/inline'>;
}
declare module 'modernizr/feature-detects/svg/smil.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/svg/smil'>;
}
declare module 'modernizr/feature-detects/templatestrings.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/templatestrings'>;
}
declare module 'modernizr/feature-detects/textarea/maxlength.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/textarea/maxlength'>;
}
declare module 'modernizr/feature-detects/touchevents.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/touchevents'>;
}
declare module 'modernizr/feature-detects/typed-arrays.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/typed-arrays'>;
}
declare module 'modernizr/feature-detects/unicode-range.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/unicode-range'>;
}
declare module 'modernizr/feature-detects/unicode.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/unicode'>;
}
declare module 'modernizr/feature-detects/url/bloburls.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/url/bloburls'>;
}
declare module 'modernizr/feature-detects/url/data-uri.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/url/data-uri'>;
}
declare module 'modernizr/feature-detects/url/parser.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/url/parser'>;
}
declare module 'modernizr/feature-detects/url/urlsearchparams.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/url/urlsearchparams'>;
}
declare module 'modernizr/feature-detects/userdata.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/userdata'>;
}
declare module 'modernizr/feature-detects/vibration.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/vibration'>;
}
declare module 'modernizr/feature-detects/video.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/video'>;
}
declare module 'modernizr/feature-detects/video/autoplay.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/video/autoplay'>;
}
declare module 'modernizr/feature-detects/video/crossorigin.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/video/crossorigin'>;
}
declare module 'modernizr/feature-detects/video/loop.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/video/loop'>;
}
declare module 'modernizr/feature-detects/video/preload.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/video/preload'>;
}
declare module 'modernizr/feature-detects/vml.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/vml'>;
}
declare module 'modernizr/feature-detects/web-intents.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/web-intents'>;
}
declare module 'modernizr/feature-detects/webanimations.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/webanimations'>;
}
declare module 'modernizr/feature-detects/webauthn/publickeycredential.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/webauthn/publickeycredential'>;
}
declare module 'modernizr/feature-detects/webgl.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/webgl'>;
}
declare module 'modernizr/feature-detects/webgl/extensions.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/webgl/extensions'>;
}
declare module 'modernizr/feature-detects/webrtc/datachannel.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/webrtc/datachannel'>;
}
declare module 'modernizr/feature-detects/webrtc/getusermedia.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/webrtc/getusermedia'>;
}
declare module 'modernizr/feature-detects/webrtc/peerconnection.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/webrtc/peerconnection'>;
}
declare module 'modernizr/feature-detects/websockets.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/websockets'>;
}
declare module 'modernizr/feature-detects/websockets/binary.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/websockets/binary'>;
}
declare module 'modernizr/feature-detects/window/atob-btoa.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/window/atob-btoa'>;
}
declare module 'modernizr/feature-detects/window/framed.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/window/framed'>;
}
declare module 'modernizr/feature-detects/window/matchmedia.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/window/matchmedia'>;
}
declare module 'modernizr/feature-detects/workers/blobworkers.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/workers/blobworkers'>;
}
declare module 'modernizr/feature-detects/workers/dataworkers.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/workers/dataworkers'>;
}
declare module 'modernizr/feature-detects/workers/sharedworkers.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/workers/sharedworkers'>;
}
declare module 'modernizr/feature-detects/workers/transferables.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/workers/transferables'>;
}
declare module 'modernizr/feature-detects/workers/webworkers.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/workers/webworkers'>;
}
declare module 'modernizr/feature-detects/xdomainrequest.js' {
  declare module.exports: $Exports<'modernizr/feature-detects/xdomainrequest'>;
}
declare module 'modernizr/lib/build-query.js' {
  declare module.exports: $Exports<'modernizr/lib/build-query'>;
}
declare module 'modernizr/lib/build.js' {
  declare module.exports: $Exports<'modernizr/lib/build'>;
}
declare module 'modernizr/lib/cli.js' {
  declare module.exports: $Exports<'modernizr/lib/cli'>;
}
declare module 'modernizr/lib/generate-banner.js' {
  declare module.exports: $Exports<'modernizr/lib/generate-banner'>;
}
declare module 'modernizr/lib/generate-license.js' {
  declare module.exports: $Exports<'modernizr/lib/generate-license'>;
}
declare module 'modernizr/lib/metadata.js' {
  declare module.exports: $Exports<'modernizr/lib/metadata'>;
}
declare module 'modernizr/lib/options.js' {
  declare module.exports: $Exports<'modernizr/lib/options'>;
}
declare module 'modernizr/src/addTest.js' {
  declare module.exports: $Exports<'modernizr/src/addTest'>;
}
declare module 'modernizr/src/atRule.js' {
  declare module.exports: $Exports<'modernizr/src/atRule'>;
}
declare module 'modernizr/src/classes.js' {
  declare module.exports: $Exports<'modernizr/src/classes'>;
}
declare module 'modernizr/src/computedStyle.js' {
  declare module.exports: $Exports<'modernizr/src/computedStyle'>;
}
declare module 'modernizr/src/contains.js' {
  declare module.exports: $Exports<'modernizr/src/contains'>;
}
declare module 'modernizr/src/createElement.js' {
  declare module.exports: $Exports<'modernizr/src/createElement'>;
}
declare module 'modernizr/src/cssomPrefixes.js' {
  declare module.exports: $Exports<'modernizr/src/cssomPrefixes'>;
}
declare module 'modernizr/src/cssToDOM.js' {
  declare module.exports: $Exports<'modernizr/src/cssToDOM'>;
}
declare module 'modernizr/src/docElement.js' {
  declare module.exports: $Exports<'modernizr/src/docElement'>;
}
declare module 'modernizr/src/domPrefixes.js' {
  declare module.exports: $Exports<'modernizr/src/domPrefixes'>;
}
declare module 'modernizr/src/domToCSS.js' {
  declare module.exports: $Exports<'modernizr/src/domToCSS'>;
}
declare module 'modernizr/src/fnBind.js' {
  declare module.exports: $Exports<'modernizr/src/fnBind'>;
}
declare module 'modernizr/src/generate.js' {
  declare module.exports: $Exports<'modernizr/src/generate'>;
}
declare module 'modernizr/src/getBody.js' {
  declare module.exports: $Exports<'modernizr/src/getBody'>;
}
declare module 'modernizr/src/hasEvent.js' {
  declare module.exports: $Exports<'modernizr/src/hasEvent'>;
}
declare module 'modernizr/src/hasOwnProp.js' {
  declare module.exports: $Exports<'modernizr/src/hasOwnProp'>;
}
declare module 'modernizr/src/html5printshiv.js' {
  declare module.exports: $Exports<'modernizr/src/html5printshiv'>;
}
declare module 'modernizr/src/html5shiv.js' {
  declare module.exports: $Exports<'modernizr/src/html5shiv'>;
}
declare module 'modernizr/src/injectElementWithStyles.js' {
  declare module.exports: $Exports<'modernizr/src/injectElementWithStyles'>;
}
declare module 'modernizr/src/inputElem.js' {
  declare module.exports: $Exports<'modernizr/src/inputElem'>;
}
declare module 'modernizr/src/is.js' {
  declare module.exports: $Exports<'modernizr/src/is'>;
}
declare module 'modernizr/src/isSVG.js' {
  declare module.exports: $Exports<'modernizr/src/isSVG'>;
}
declare module 'modernizr/src/load.js' {
  declare module.exports: $Exports<'modernizr/src/load'>;
}
declare module 'modernizr/src/modElem.js' {
  declare module.exports: $Exports<'modernizr/src/modElem'>;
}
declare module 'modernizr/src/Modernizr.js' {
  declare module.exports: $Exports<'modernizr/src/Modernizr'>;
}
declare module 'modernizr/src/ModernizrProto.js' {
  declare module.exports: $Exports<'modernizr/src/ModernizrProto'>;
}
declare module 'modernizr/src/mq.js' {
  declare module.exports: $Exports<'modernizr/src/mq'>;
}
declare module 'modernizr/src/mStyle.js' {
  declare module.exports: $Exports<'modernizr/src/mStyle'>;
}
declare module 'modernizr/src/nativeTestProps.js' {
  declare module.exports: $Exports<'modernizr/src/nativeTestProps'>;
}
declare module 'modernizr/src/omPrefixes.js' {
  declare module.exports: $Exports<'modernizr/src/omPrefixes'>;
}
declare module 'modernizr/src/prefixed.js' {
  declare module.exports: $Exports<'modernizr/src/prefixed'>;
}
declare module 'modernizr/src/prefixedCSS.js' {
  declare module.exports: $Exports<'modernizr/src/prefixedCSS'>;
}
declare module 'modernizr/src/prefixedCSSValue.js' {
  declare module.exports: $Exports<'modernizr/src/prefixedCSSValue'>;
}
declare module 'modernizr/src/prefixes.js' {
  declare module.exports: $Exports<'modernizr/src/prefixes'>;
}
declare module 'modernizr/src/roundedEquals.js' {
  declare module.exports: $Exports<'modernizr/src/roundedEquals'>;
}
declare module 'modernizr/src/setClasses.js' {
  declare module.exports: $Exports<'modernizr/src/setClasses'>;
}
declare module 'modernizr/src/slice.js' {
  declare module.exports: $Exports<'modernizr/src/slice'>;
}
declare module 'modernizr/src/testAllProps.js' {
  declare module.exports: $Exports<'modernizr/src/testAllProps'>;
}
declare module 'modernizr/src/testDOMProps.js' {
  declare module.exports: $Exports<'modernizr/src/testDOMProps'>;
}
declare module 'modernizr/src/testProp.js' {
  declare module.exports: $Exports<'modernizr/src/testProp'>;
}
declare module 'modernizr/src/testProps.js' {
  declare module.exports: $Exports<'modernizr/src/testProps'>;
}
declare module 'modernizr/src/testPropsAll.js' {
  declare module.exports: $Exports<'modernizr/src/testPropsAll'>;
}
declare module 'modernizr/src/testRunner.js' {
  declare module.exports: $Exports<'modernizr/src/testRunner'>;
}
declare module 'modernizr/src/tests.js' {
  declare module.exports: $Exports<'modernizr/src/tests'>;
}
declare module 'modernizr/src/testStyles.js' {
  declare module.exports: $Exports<'modernizr/src/testStyles'>;
}
declare module 'modernizr/src/testXhrType.js' {
  declare module.exports: $Exports<'modernizr/src/testXhrType'>;
}
declare module 'modernizr/src/toStringFn.js' {
  declare module.exports: $Exports<'modernizr/src/toStringFn'>;
}
