// flow-typed signature: 51c17647b06a8f63c8545b8ca948eec4
// flow-typed version: <<STUB>>/precss_v^1.4.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'precss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'precss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'precss/gulpfile' {
  declare module.exports: any;
}

declare module 'precss/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'precss/gulpfile.js' {
  declare module.exports: $Exports<'precss/gulpfile'>;
}
declare module 'precss/index' {
  declare module.exports: $Exports<'precss'>;
}
declare module 'precss/index.js' {
  declare module.exports: $Exports<'precss'>;
}
declare module 'precss/test/index.js' {
  declare module.exports: $Exports<'precss/test/index'>;
}
