// flow-typed signature: 7633baffb2f5c0d76539bcee6560ba96
// flow-typed version: <<STUB>>/react-overdrive_v^0.0.10/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-overdrive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-overdrive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-overdrive/lib/Overdrive.min' {
  declare module.exports: any;
}

declare module 'react-overdrive/src/index' {
  declare module.exports: any;
}

declare module 'react-overdrive/src/overdrive' {
  declare module.exports: any;
}

declare module 'react-overdrive/src/prefix' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-overdrive/lib/Overdrive.min.js' {
  declare module.exports: $Exports<'react-overdrive/lib/Overdrive.min'>;
}
declare module 'react-overdrive/src/index.js' {
  declare module.exports: $Exports<'react-overdrive/src/index'>;
}
declare module 'react-overdrive/src/overdrive.js' {
  declare module.exports: $Exports<'react-overdrive/src/overdrive'>;
}
declare module 'react-overdrive/src/prefix.js' {
  declare module.exports: $Exports<'react-overdrive/src/prefix'>;
}
