// flow-typed signature: 7df47b6d156f570691f76c8b16109705
// flow-typed version: <<STUB>>/react-notification_v^6.5.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-notification'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-notification' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-notification/dist/defaultPropTypes' {
  declare module.exports: any;
}

declare module 'react-notification/dist/index' {
  declare module.exports: any;
}

declare module 'react-notification/dist/notification' {
  declare module.exports: any;
}

declare module 'react-notification/dist/notificationStack' {
  declare module.exports: any;
}

declare module 'react-notification/dist/stackedNotification' {
  declare module.exports: any;
}

declare module 'react-notification/examples/notification-tree/index' {
  declare module.exports: any;
}

declare module 'react-notification/examples/server' {
  declare module.exports: any;
}

declare module 'react-notification/examples/single-notification/index' {
  declare module.exports: any;
}

declare module 'react-notification/examples/webpack.config' {
  declare module.exports: any;
}

declare module 'react-notification/test/mockNotification' {
  declare module.exports: any;
}

declare module 'react-notification/test/notification' {
  declare module.exports: any;
}

declare module 'react-notification/test/notificationStack' {
  declare module.exports: any;
}

declare module 'react-notification/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-notification/dist/defaultPropTypes.js' {
  declare module.exports: $Exports<'react-notification/dist/defaultPropTypes'>;
}
declare module 'react-notification/dist/index.js' {
  declare module.exports: $Exports<'react-notification/dist/index'>;
}
declare module 'react-notification/dist/notification.js' {
  declare module.exports: $Exports<'react-notification/dist/notification'>;
}
declare module 'react-notification/dist/notificationStack.js' {
  declare module.exports: $Exports<'react-notification/dist/notificationStack'>;
}
declare module 'react-notification/dist/stackedNotification.js' {
  declare module.exports: $Exports<'react-notification/dist/stackedNotification'>;
}
declare module 'react-notification/examples/notification-tree/index.js' {
  declare module.exports: $Exports<'react-notification/examples/notification-tree/index'>;
}
declare module 'react-notification/examples/server.js' {
  declare module.exports: $Exports<'react-notification/examples/server'>;
}
declare module 'react-notification/examples/single-notification/index.js' {
  declare module.exports: $Exports<'react-notification/examples/single-notification/index'>;
}
declare module 'react-notification/examples/webpack.config.js' {
  declare module.exports: $Exports<'react-notification/examples/webpack.config'>;
}
declare module 'react-notification/test/mockNotification.js' {
  declare module.exports: $Exports<'react-notification/test/mockNotification'>;
}
declare module 'react-notification/test/notification.js' {
  declare module.exports: $Exports<'react-notification/test/notification'>;
}
declare module 'react-notification/test/notificationStack.js' {
  declare module.exports: $Exports<'react-notification/test/notificationStack'>;
}
declare module 'react-notification/test/setup.js' {
  declare module.exports: $Exports<'react-notification/test/setup'>;
}
