// flow-typed signature: 1d8d10ee6ed46b1683ca4c469b85dcc3
// flow-typed version: <<STUB>>/rename_v^1.0.4/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rename'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rename' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rename/lib/parse' {
  declare module.exports: any;
}

declare module 'rename/lib/stringify' {
  declare module.exports: any;
}

declare module 'rename/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rename/index' {
  declare module.exports: $Exports<'rename'>;
}
declare module 'rename/index.js' {
  declare module.exports: $Exports<'rename'>;
}
declare module 'rename/lib/parse.js' {
  declare module.exports: $Exports<'rename/lib/parse'>;
}
declare module 'rename/lib/stringify.js' {
  declare module.exports: $Exports<'rename/lib/stringify'>;
}
declare module 'rename/lib/util.js' {
  declare module.exports: $Exports<'rename/lib/util'>;
}
