// flow-typed signature: e9ea03f07b806ef0dabca704c4a0a742
// flow-typed version: <<STUB>>/webpack-require-from_v^1.3.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-require-from'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-require-from' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-require-from/example/a' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/b' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/c' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/dist/0.a3e90d5bc6f920451d06.worker' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/dist/0.main' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/dist/a3e90d5bc6f920451d06.worker' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/dist/main' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/dist/worker.main' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/globals' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/index' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/webpack.config' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/worker-module' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/worker' {
  declare module.exports: any;
}

declare module 'webpack-require-from/src/codeBuilders' {
  declare module.exports: any;
}

declare module 'webpack-require-from/src/constants' {
  declare module.exports: any;
}

declare module 'webpack-require-from/src/helpers' {
  declare module.exports: any;
}

declare module 'webpack-require-from/src/plugin' {
  declare module.exports: any;
}

declare module 'webpack-require-from/test/common/common.test' {
  declare module.exports: any;
}

declare module 'webpack-require-from/test/common/playground' {
  declare module.exports: any;
}

declare module 'webpack-require-from/test/common/src/index' {
  declare module.exports: any;
}

declare module 'webpack-require-from/test/common/src/moduleB' {
  declare module.exports: any;
}

declare module 'webpack-require-from/test/common/src/moduleC' {
  declare module.exports: any;
}

declare module 'webpack-require-from/test/common/src/worker' {
  declare module.exports: any;
}

declare module 'webpack-require-from/test/common/webpack.config.shared' {
  declare module.exports: any;
}

declare module 'webpack-require-from/test/common/webworker.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-require-from/example/a.js' {
  declare module.exports: $Exports<'webpack-require-from/example/a'>;
}
declare module 'webpack-require-from/example/b.js' {
  declare module.exports: $Exports<'webpack-require-from/example/b'>;
}
declare module 'webpack-require-from/example/c.js' {
  declare module.exports: $Exports<'webpack-require-from/example/c'>;
}
declare module 'webpack-require-from/example/dist/0.a3e90d5bc6f920451d06.worker.js' {
  declare module.exports: $Exports<'webpack-require-from/example/dist/0.a3e90d5bc6f920451d06.worker'>;
}
declare module 'webpack-require-from/example/dist/0.main.js' {
  declare module.exports: $Exports<'webpack-require-from/example/dist/0.main'>;
}
declare module 'webpack-require-from/example/dist/a3e90d5bc6f920451d06.worker.js' {
  declare module.exports: $Exports<'webpack-require-from/example/dist/a3e90d5bc6f920451d06.worker'>;
}
declare module 'webpack-require-from/example/dist/main.js' {
  declare module.exports: $Exports<'webpack-require-from/example/dist/main'>;
}
declare module 'webpack-require-from/example/dist/worker.main.js' {
  declare module.exports: $Exports<'webpack-require-from/example/dist/worker.main'>;
}
declare module 'webpack-require-from/example/globals.js' {
  declare module.exports: $Exports<'webpack-require-from/example/globals'>;
}
declare module 'webpack-require-from/example/index.js' {
  declare module.exports: $Exports<'webpack-require-from/example/index'>;
}
declare module 'webpack-require-from/example/webpack.config.js' {
  declare module.exports: $Exports<'webpack-require-from/example/webpack.config'>;
}
declare module 'webpack-require-from/example/worker-module.js' {
  declare module.exports: $Exports<'webpack-require-from/example/worker-module'>;
}
declare module 'webpack-require-from/example/worker.js' {
  declare module.exports: $Exports<'webpack-require-from/example/worker'>;
}
declare module 'webpack-require-from/index' {
  declare module.exports: $Exports<'webpack-require-from'>;
}
declare module 'webpack-require-from/index.js' {
  declare module.exports: $Exports<'webpack-require-from'>;
}
declare module 'webpack-require-from/src/codeBuilders.js' {
  declare module.exports: $Exports<'webpack-require-from/src/codeBuilders'>;
}
declare module 'webpack-require-from/src/constants.js' {
  declare module.exports: $Exports<'webpack-require-from/src/constants'>;
}
declare module 'webpack-require-from/src/helpers.js' {
  declare module.exports: $Exports<'webpack-require-from/src/helpers'>;
}
declare module 'webpack-require-from/src/plugin.js' {
  declare module.exports: $Exports<'webpack-require-from/src/plugin'>;
}
declare module 'webpack-require-from/test/common/common.test.js' {
  declare module.exports: $Exports<'webpack-require-from/test/common/common.test'>;
}
declare module 'webpack-require-from/test/common/playground.js' {
  declare module.exports: $Exports<'webpack-require-from/test/common/playground'>;
}
declare module 'webpack-require-from/test/common/src/index.js' {
  declare module.exports: $Exports<'webpack-require-from/test/common/src/index'>;
}
declare module 'webpack-require-from/test/common/src/moduleB.js' {
  declare module.exports: $Exports<'webpack-require-from/test/common/src/moduleB'>;
}
declare module 'webpack-require-from/test/common/src/moduleC.js' {
  declare module.exports: $Exports<'webpack-require-from/test/common/src/moduleC'>;
}
declare module 'webpack-require-from/test/common/src/worker.js' {
  declare module.exports: $Exports<'webpack-require-from/test/common/src/worker'>;
}
declare module 'webpack-require-from/test/common/webpack.config.shared.js' {
  declare module.exports: $Exports<'webpack-require-from/test/common/webpack.config.shared'>;
}
declare module 'webpack-require-from/test/common/webworker.test.js' {
  declare module.exports: $Exports<'webpack-require-from/test/common/webworker.test'>;
}
