// flow-typed signature: a911078bc67d3f0d22957ade565ea73c
// flow-typed version: <<STUB>>/workbox-webpack-plugin_v^3.4.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'workbox-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'workbox-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'workbox-webpack-plugin/build/generate-sw' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/index' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/inject-manifest' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/convert-string-to-asset' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/format-manifest-filename' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/get-asset-hash' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/get-default-config' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/get-workbox-sw-imports' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/read-file-wrapper' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/relative-to-output-path' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/resolve-webpack-url' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/sanitize-config' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/stringify-manifest' {
  declare module.exports: any;
}

declare module 'workbox-webpack-plugin/build/lib/warn-about-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'workbox-webpack-plugin/build/generate-sw.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/generate-sw'>;
}
declare module 'workbox-webpack-plugin/build/index.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/index'>;
}
declare module 'workbox-webpack-plugin/build/inject-manifest.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/inject-manifest'>;
}
declare module 'workbox-webpack-plugin/build/lib/convert-string-to-asset.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/convert-string-to-asset'>;
}
declare module 'workbox-webpack-plugin/build/lib/format-manifest-filename.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/format-manifest-filename'>;
}
declare module 'workbox-webpack-plugin/build/lib/get-asset-hash.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/get-asset-hash'>;
}
declare module 'workbox-webpack-plugin/build/lib/get-default-config.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/get-default-config'>;
}
declare module 'workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation'>;
}
declare module 'workbox-webpack-plugin/build/lib/get-workbox-sw-imports.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/get-workbox-sw-imports'>;
}
declare module 'workbox-webpack-plugin/build/lib/read-file-wrapper.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/read-file-wrapper'>;
}
declare module 'workbox-webpack-plugin/build/lib/relative-to-output-path.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/relative-to-output-path'>;
}
declare module 'workbox-webpack-plugin/build/lib/resolve-webpack-url.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/resolve-webpack-url'>;
}
declare module 'workbox-webpack-plugin/build/lib/sanitize-config.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/sanitize-config'>;
}
declare module 'workbox-webpack-plugin/build/lib/stringify-manifest.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/stringify-manifest'>;
}
declare module 'workbox-webpack-plugin/build/lib/warn-about-config.js' {
  declare module.exports: $Exports<'workbox-webpack-plugin/build/lib/warn-about-config'>;
}
